---

- name: Configure domain for OpenLDAP in debconf
  debconf:
    name: 'slapd'
    question: '{{ item.key }}'
    vtype: '{{ item.value.type }}'
    value: '{{ item.value.value }}'
  with_dict:
    slapd/domain:            { type: string,   value: '{{slapd_domain}}' }
    shared/organization:     { type: string,   value: '{{slapd_domain}}' }
    slapd/backend:           { type: string,   value: '{{slapd_backend|upper}}' }
    slapd/no_configuration:  { type: boolean,  value:  'false' }
    slapd/move_old_database: { type: boolean,  value:  'true' }
    slapd/allow_ldap_v2:     { type: boolean,  value:  'false' }
    slapd/password1:         { type: password, value: '{{slapd_root_password}}' }
    slapd/password2:         { type: password, value: '{{slapd_root_password}}' }
  notify: restart slapd

- name: Install OpenLDAP packages
  apt: name={{ item }}
  with_items:
  - slapd
  - ldap-utils
  - python-ldap
  - ldapvi
